apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test2"
  labels:
    system: web-apps
  links:
    - url: https://github.com/RohanAwasthi/test234
      title: "test"
      icon: code
  tags:
    - java
    - azure
    - applicationtype-webapplication
  annotations:
    jenkins.io/github-folder: 'apache-azure-app/test'
    jenkins.io/job-full-name: 'apache-azure-app/test'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  RohanAwasthi/test234
    backstage.io/linguist: https://github.com/RohanAwasthi/test234
    azure.com/tag-selector: 'pid/test'
spec:
  type: service
  lifecycle: development
  owner: user:default/adithya.bhairanje
